apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/${{ secrets.DOCKER_USERNAME }}/flask-app-repo:latest  # Use your Docker Hub image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Matches the app label in the deployment
  ports:
    - protocol: TCP
      port: 80  # Expose to port 80 externally
      targetPort: 5000  # The internal port of the Flask app
  type: NodePort  # Change to LoadBalancer for cloud-based clusters
